name: CI/CD pipeline
run-name: Building and deploying factorial app
on:
  push:
    branches:
    - main

jobs:
  Test:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - run: python3 -m unittest test_factorial.py

  Build-deploy:
    needs: Test
    runs-on: ubuntu-20.04
    steps:
      - uses: docker/setup-buildx-action@v3
      - uses: dopplerhq/cli-action@v3
      - uses: docker/login-action@v3
        with:
          username: ${{ env.DOCKER_HUB_NAME }}
          password: ${{ env.DOCKER_HUB_TOKEN }}
      - uses: docker/build-push-action@v6
        with:
          push: true
          tags: ${{ env.DOCKER_HUB_NAME }}/my_app:latest